[package]
name = "till"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["cargo"] }
regex = "1.5.4"
rand = "0.8.4"
tokio = { version = "1", features = ["full"] }
tabled = "0.15.0"
