[package]
name = "till"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.1", features = ["cargo", "derive"] }
clap_derive = "4.5.0"
tabled = "0.15.0"
hickory-client = "0.24.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"